; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\arant\AppData\Local\Temp\.NETFramework,Version=4.6.1.AssemblyAttributes.cpp"
