; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27030.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Arantxa\AppData\Local\Temp\.NETFramework,Version=4.6.1.AssemblyAttributes.cpp"
